In [19]:
import numpy as np

my_list = list(range(1000000))

%time for i in range(10): my_list2=[i*2 for i in my_list]

my_arr = np.arange(1000000)

%time for i in range(10): my_arr = my_arr*2
    
my_arr2 = np.arange(10)
my_arr2

CPU times: user 449 ms, sys: 97.4 ms, total: 546 ms
Wall time: 547 ms
CPU times: user 8.07 ms, sys: 71 µs, total: 8.14 ms
Wall time: 8.26 ms


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
import numpy as np

data = np.random.randn(2,4)
print(data)
data = data *2
print(data)


data.shape
data.dtype

[[-1.10837797 -0.75944527 -0.88616182  0.57027295]
 [-1.27347951  0.08607507  0.61929115  0.26478309]]
[[-2.21675593 -1.51889054 -1.77232365  1.1405459 ]
 [-2.54695902  0.17215015  1.2385823   0.52956619]]


dtype('float64')